version: '3.4'

networks:
  dev:
    driver: bridge

services:
  realestate:
    image: realestate
    container_name: realestate
    restart: always
    networks:
      - dev
    ports:
      - "80:80"
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev
    volumes:
      - data:/var/lib/mysql # Persist data even after container is destroyed
    ports:
      - "3306:3306"
