version: '3.4'

networks:
  dev:
    driver: bridge
volumes:
  mysql_data:

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  migrations:
    image: service-migrations
    container_name: service-migrations
    build:
      target: migrations
    depends_on:
        - mysql_db

  realestate:
    image: realestate
    container_name: realestate
    restart: always
    networks:
      - dev
    depends_on:
      - mysql_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
  
