version: '3.4'

networks:
  dev:
    driver: bridge

services:
  realestate:
    image: realestate
    container_name: realestate
    restart: always
    networks:
      - dev
    depends_on:
      - mysql_db
    ports:
      - "81:80"
  
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev
    ports:
      - "3306:3306"
